import { GoogleGenerativeAI } from "@google/generative-ai";
import fs from "fs";


const genAI = new GoogleGenerativeAI(process.env.GEMINI_KEY || "");


function fileToGenerativePart(filePath: string, mimeType: string) {
  return {
    inlineData: {
      data: Buffer.from(fs.readFileSync(filePath)).toString("base64"),
      mimeType,
    },
  };
}

export type GeminiAnalysisResult = {
  colorTone: "WARM" | "COOL" | "NEUTRAL" | "DARK" | "LIGHT";
  palette: string[];
};

export class GeminiService {
  async analyzeImage(
    filePath: string,
    mimeType: string,
  ): Promise<GeminiAnalysisResult | null> {
    if (!process.env.GEMINI_KEY) {
      console.warn("GEMINI_KEY is not set. Skipping image analysis.");
      return null;
    }

    try {
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash",
        generationConfig: { responseMimeType: "application/json" },
      });

      const prompt = `
Output strictly valid JSON.
{
  "colorTone": "choose exactly one of: WARM, COOL, NEUTRAL, DARK, LIGHT",
  "palette": ["#Hex1", "#Hex2", "#Hex3"]
}
      `;

      const imagePart = fileToGenerativePart(filePath, mimeType);

      const result = await model.generateContent([prompt, imagePart]);
      let responseText = result.response.text();

      
      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        responseText = jsonMatch[0];
      }

      const parsed = JSON.parse(responseText.trim());

      const normalizedTone = String(parsed.colorTone).toUpperCase();

      
      if (
        !["WARM", "COOL", "NEUTRAL", "DARK", "LIGHT"].includes(
          normalizedTone,
        ) ||
        !Array.isArray(parsed.palette)
      ) {
        console.error("Gemini returned invalid structure:", parsed);
        throw new Error("Invalid format received from Gemini");
      }

      return {
        colorTone: normalizedTone as GeminiAnalysisResult["colorTone"],
        palette: parsed.palette.slice(0, 5), 
      };
    } catch (error) {
      console.error("Error analyzing image with Gemini:", error);
      return null;
    }
  }

  async generateImage(prompt: string, modelName: string): Promise<Buffer> {
    if (!process.env.GEMINI_KEY) {
      throw new Error("GEMINI_KEY is not set.");
    }

    try {
      const model = genAI.getGenerativeModel({ model: modelName });

      const result = await model.generateContent(prompt);
      const response = await result.response;

      const candidates = response.candidates;
      const firstCandidate = candidates?.[0];
      if (firstCandidate && firstCandidate.content?.parts) {
        const parts = firstCandidate.content.parts;
        if (parts.length > 0) {
          const inlineData = parts.find((p: any) => p.inlineData)?.inlineData;
          if (inlineData && inlineData.data) {
            return Buffer.from(inlineData.data, "base64");
          }
        }

        
        const text = response.text();
        if (text) {
          throw new Error(`Model returned text instead of an image: ${text.substring(0, 50)}... Make sure the chosen model supports image generation.`);
        }
      }

      throw new Error("No output generated by the model");
    } catch (error) {
      console.error("Error generating image with Gemini:", error);
      throw error;
    }
  }

  async generateEmbedding(text: string): Promise<number[]> {
    if (!process.env.GEMINI_KEY) {
      throw new Error("GEMINI_KEY is not set.");
    }

    try {
      const model = genAI.getGenerativeModel({
        model: "models/gemini-embedding-001",
      });
      const result = await model.embedContent(text);
      return result.embedding.values;
    } catch (error) {
      console.error("Error generating embedding with Gemini:", error);
      return [];
    }
  }
}
